version: 2
jobs:
  build:
    docker:
      - image: circleci/classic:201808-01
    working_directory: ~/ca
    steps:
      - checkout
      - run: 
        name: "executing mvn clean install"
        command: |
          echo "my first build"
      - mvn -DskipTests clean install 