version: 2
jobs:
  docker_build:
    docker:
      # specify the version you desire here
      - image: circleci/buildpack-deps
    working_directory: ~/repo
    steps:
        - checkout
        - run: echo "docker"
        - setup_remote_docker
        - run:
            command: |
              TAG="0.1.${CIRCLE_BUILD_NUM}"
              docker build -t jeanjoseph/circi:$TAG ~/repo/docker
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              docker push jeanjoseph/circi:$TAG


workflows:
  version: 2
  my-workflow:
    jobs: 
      - docker_build
